spring.application.name=workout_ledger_backend_java
jwt.secret=your-super-secret-key
jwt.expiration=86400000
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email
google.client-id=
server.forward-headers-strategy=framework
